# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/Instrumentacion/Boris FPGA/Unidad_Conteo_Coincidencias/Unidad_Conteo_Coincidencias.cache/wt} [current_project]
set_property parent.project_path {D:/Instrumentacion/Boris FPGA/Unidad_Conteo_Coincidencias/Unidad_Conteo_Coincidencias.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo {d:/Instrumentacion/Boris FPGA/Unidad_Conteo_Coincidencias/Unidad_Conteo_Coincidencias.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {D:/Instrumentacion/Boris FPGA/UCC_21.08.2018/UCC_SING/UCC_SING/Super_uart_derecho.vhd}
  {D:/Instrumentacion/Boris FPGA/UCC_21.08.2018/UCC_SING/UCC_SING/UARTReceiver.vhd}
  {D:/Instrumentacion/Boris FPGA/UCC_21.08.2018/UCC_SING/UCC_SING/UARTTransmitter.vhd}
  {D:/Instrumentacion/Boris FPGA/Unidad_Conteo_Coincidencias/Unidad_Conteo_Coincidencias.srcs/sources_1/new/counter.vhd}
  {D:/Instrumentacion/Boris FPGA/Unidad_Conteo_Coincidencias/Unidad_Conteo_Coincidencias.srcs/sources_1/new/time_window.vhd}
  {D:/Instrumentacion/Boris FPGA/UCC_21.08.2018/UCC_SING/UCC_SING/CPU_COINC.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/Instrumentacion/Boris FPGA/Unidad_Conteo_Coincidencias/Unidad_Conteo_Coincidencias.srcs/constrs_1/new/CPU_COINC.xdc}}
set_property used_in_implementation false [get_files {{D:/Instrumentacion/Boris FPGA/Unidad_Conteo_Coincidencias/Unidad_Conteo_Coincidencias.srcs/constrs_1/new/CPU_COINC.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top UCC_SING -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef UCC_SING.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file UCC_SING_utilization_synth.rpt -pb UCC_SING_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
